### ISSUE TITLE
Raspberry Pi 4 Sink Service

### ISSUE THREAD

**Issue by chrylarson** [wirepas/raspberry-gateway-image#9]
I'm trying to get a Raspberry Pi4 to run the sinkService and running into issues with finding the correct port.
Have you run the sinkService on an RPi4? Any guidance would be appreciated.
`./sinkService -p /dev/ttyAMA0 -b 125000 -I 0`
I'm running on Ubuntu 20.10 since the end product is a Snap app.

**Comment by GwendalRaoul** [comment]
What kind of sink did you plug to your Rpi4 ?
